#!/bin/bash
# This file is being used so that users don't have to unset env vars manually
HERE="$(dirname "$(readlink -f "${0}")")"
unset QTDIR; unset QT_PLUGIN_PATH ; unset LD_LIBRARY_PATH
exec "${HERE}/usr/bin/linuxdeployqt" "$@"
