#!/bin/bash

#
# The missing Qt downloader for Travis CI
# Ideally something like this (but done properly) would be offered by Qt officially
#
# To make the exports work, this file needs to be sourced rather than executed
#

# Install 7zip if it is not there yet
which 7zr >/dev/null 2>&1 || ( sudo apt-get update ; sudo apt-get -y install p7zip )

QTCOMPILER="gcc_64"

if [ "$QTCOMPILER" == "gcc_64" ] ; then QTARCH="x64" ; fi

# Get the available versions
QTVERSIONS=$(wget -q "http://download.qt.io/online/qtsdkrepository/linux_x64/desktop/" -O - | grep qt5_ | cut -d '"' -f 12 | grep -v examples | sed -e 's|/||g' | sort -V -r)
echo "Qt versions available from download.qt.io:"
echo "$QTVERSIONS"
if [ -z $QTVERSION ] ; then QTVERSION=$(echo $QTVERSIONS | cut -d " " -f 1) ; fi
echo "Using $QTVERSION; override by setting \$QTVERSION"
sed -i -e 's|^QT_EDITION =.*|QT_EDITION = OpenSource|g' /home/me/Qt5.10.0b/5.10.0/gcc_64/mkspecs/qconfig.pri
echo ""

# List the Qt components for that version
URL="http://download.qt.io/online/qtsdkrepository/linux_$QTARCH/desktop/$QTVERSION/"
QTCOMPONENTS=$(wget -q "$URL" -O - | cut -d '"' -f 12 | grep "$QTCOMPILER" | sed -e 's|/||g' | sort)
echo "Qt components available from download.qt.io:"
echo "$QTCOMPONENTS"
if [ -z $QTCOMPONENT ] ; then QTCOMPONENT=$(echo $QTCOMPONENTS | cut -d " " -f 1) ; fi
echo "Using $QTCOMPONENT; override by setting \$QTCOMPONENT"
echo ""

# List the Qt subversions
URL="http://download.qt.io/online/qtsdkrepository/linux_$QTARCH/desktop/$QTVERSION/$QTCOMPONENT"
QTSUBVERSIONS=$(wget -q "$URL" -O - | cut -d '"' -f 12 | sed -e 's|/||g' | grep "meta.7z$" | sort -V -r | uniq | sed -e 's|meta.7z||g')
echo "Qt subversions available from download.qt.io:"
echo "$QTSUBVERSIONS"
if [ -z $QTSUBVERSION ] ; then QTSUBVERSION=$(echo $QTSUBVERSIONS | cut -d " " -f 1) ; fi
echo "Using $QTSUBVERSION; override by setting \$QTSUBVERSION"
echo ""

# List the Qt subcomponents for that subversion
URL="http://download.qt.io/online/qtsdkrepository/linux_$QTARCH/desktop/$QTVERSION/$QTCOMPONENT/"
wget -q "$URL" -O - | cut -d '"' -f 12 | sed -e 's|/||g' | grep "7z$" | grep $QTSUBVERSION | sort | sed -e 's|'$QTSUBVERSION'||g' | cut -d "-" -f 1
echo "Qt subcomponents available from download.qt.io:"
echo "$QTSUBCOMPONENTS"
if [ -z $QTSUBCOMPONENT ] ; then QTSUBCOMPONENT=qtbase ; fi
echo "Using $QTSUBCOMPONENT; override by setting \$QTSUBCOMPONENT"
echo ""

FILE=$(wget -q "$URL" -O - | cut -d '"' -f 12 | sed -e 's|/||g' | grep "7z$" | grep $QTSUBVERSION | grep $QTSUBCOMPONENT)
echo "$URL$FILE"

wget -c "$URL$FILE"

if [ -z $QTTARGET ] ; then
  mkdir -p "$HOME/Qt"
  QTTARGET=$(readlink -f "$HOME/Qt")
  echo "Using $QTTARGET; override by setting \$QTTARGET"
fi

7zr x "$FILE" -o"$QTTARGET" -aoa -y >/dev/null

QTPATH=$(dirname $(find "$QTTARGET" -executable -name qmake))
if [ ! -z "$QTPATH" ] ; then echo export PATH=$QTPATH:\$PATH && export PATH=$QTPATH:$PATH && qmake -v ; fi

QTLIBPATH=$(dirname $(find "$QTTARGET" -name "libQt*Core.so" | head -n 1))
if [ ! -z "$QTLIBPATH" ] ; then echo export LD_LIBRARY_PATH=$QTLIBPATH:\$LD_LIBRARY_PATH && export LD_LIBRARY_PATH=$QTLIBPATH:$LD_LIBRARY_PATH ; fi

QTDIR=$(dirname $(dirname "$QTLIBPATH"))
if [ ! -z "$QTDIR" ] ; then
  echo export QTDIR=$QTDIR && export QTDIR=$QTDIR
  echo export PKG_CONFIG_PATH=$QTDIR/lib/pkgconfig:\$PKG_CONFIG_PATH && export PKG_CONFIG_PATH=$QTDIR/lib/pkgconfig:$PKG_CONFIG_PATH
fi

echo "Qt from qt.io seems to have hardcoded paths to /home/qt/work/install which the Qt installer also patches"
echo "http://code.qt.io/cgit/installer-framework/installer-framework.git/tree/src/libs/installer/qtpatchoperation.cpp?id=0ff7968345752395af93334b174973ebefb95048#n58"

cat > $QTPATH/qt.conf <<EOF
[Paths]
Prefix = ..
EOF

# Workaround for:
# Error: Qt license file was not found!
# Project ERROR: License check failed! Giving up ...
sed -i -e 's|^QT_EDITION =.*|QT_EDITION = OpenSource|g' "$QTDIR/mkspecs/qconfig.pri"
